version: "3.7"

services:
  postgres:
    image: postgres:12.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres

volumes:
  pg-data:
